workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    scripts:
      - name: Locate Flutter Project and Build APK
        script: |
          # البحث عن مكان ملف pubspec.yaml في أي مجلد
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -type f | head -n 1)
          
          if [ -n "$PUBSPEC_PATH" ]; then
            PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
            echo "تم العثور على مشروع Flutter في المسار: $PROJECT_DIR"
            cd "$PROJECT_DIR"
            flutter packages get
            flutter build apk --debug
          else
            echo "خطأ: لم يتم العثور على أي ملف pubspec.yaml في المستودع"
            exit 1
          fi
    artifacts:
      - "**/build/outputs/**/*.apk"
